### ISSUE TITLE
PRACTICA MARCADOR DE IMAGEN

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipo-pc-box#2]
[IMPLEMENTACIÓN DEL MODELO 3D CON MARCADOR DE IMAGEN.pdf](https://github.com/SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipo-pc-box/files/8608132/IMPLEMENTACION.DEL.MODELO.3D.CON.MARCADOR.DE.IMAGEN.pdf)

**Comment by Anthony4523** [comment]
Contiene todos los puntos requeridos de la rúbrica.
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
